# -*- coding: utf-8 -*-
"""garmin_data_lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8poDzfdPdkPMRIYMx4XITBciEjIvF6b

# Pull Data from Garmin
"""

import pandas as pd
import numpy as np
from datetime import datetime
from garminconnect import Garmin
from google.colab import userdata
import os

# --- הגדרות ---
NEW_CSV_PATH = '/content/drive/MyDrive/Garmin_Project/garmin_master_2026_rebuilt.csv'
START_DATE = "2026-01-01"

def rebuild_2026_dataset():
    try:
        # 1. התחברות לגרמין
        print("🔗 Connecting to Garmin...")
        client = Garmin(os.environ.get('garmin_email'), os.environ.get('garmin_pass'))
        client.login()

        # 2. שליפת כל הפעילויות מ-2026
        print(f"⏳ Fetching all activities since {START_DATE}...")
        activities = client.get_activities_by_date(START_DATE, datetime.now().date().isoformat())
        print(f"✅ Found {len(activities)} activities.")

        all_rows = []

        for act in activities:
            # חילוץ נתונים בסיסי
            dist_m = act.get('distance', 0)
            duration_sec = act.get('duration', 0)
            dist_km = round(dist_m / 1000, 2)
            duration_min = round(duration_sec / 60, 2)

            # חישוב אורך צעד (ס"מ)
            stride_cm = act.get('avgStrideLength', 0)
            cadence = act.get('avgCadence', 0)
            if (stride_cm == 0 or stride_cm is None) and cadence > 0 and duration_min > 0:
                total_steps = cadence * duration_min
                stride_cm = (dist_km * 100000) / total_steps if total_steps > 0 else 0

            # בניית השורה עם כל המדדים שביקשת
            row = {
                'activity_id': act.get('activityId'),
                'date': act.get('startTimeLocal'),
                'type': act.get('activityType', {}).get('typeKey'),
                'distance_km': dist_km,
                'duration_min': duration_min,
                'pace_min_km': round(duration_min / dist_km, 2) if dist_km > 0 else 0,
                'avg_hr': act.get('averageHR', 0),
                'max_hr': act.get('maxHR', 0), # השדה שתיקנו
                'cadence': round(cadence, 1),
                'stride_length_cm': round(stride_cm, 1),
                'vertical_oscillation': act.get('avgVerticalOscillation', 0),
                'ground_contact_time': act.get('avgGroundContactTime', 0),
                'elevation_gain': act.get('elevationGain', 0),
                'elevation_loss': act.get('elevationLoss', 0),
                'aerobic_te': act.get('aerobicTrainingEffect', 0),
                'anaerobic_te': act.get('anaerobicTrainingEffect', 0),
                'vo2_max': act.get('vO2MaxValue', 0),
                'calories': act.get('calories', 0)
            }
            all_rows.append(row)

        # 3. יצירת DataFrame וסידור לפי תאריך
        df = pd.DataFrame(all_rows)
        df['date'] = pd.to_datetime(df['date'])
        df = df.sort_values('date').reset_index(drop=True)

        # 4. חישוב מדדי עומס (Workload & ACWR)
        print("📈 Calculating training metrics...")
        df['workload'] = df['distance_km'] * (df['avg_hr'] / 100)
        df['acute'] = df['workload'].rolling(window=7, min_periods=1).mean()
        df['chronic'] = df['workload'].rolling(window=28, min_periods=1).mean()
        df['acwr'] = (df['acute'] / df['chronic']).replace([np.inf, -np.inf], 0).fillna(0)

        # 5. שמירה לקובץ חדש
        df.to_csv(NEW_CSV_PATH, index=False)
        print(f"🏁 DONE! New database saved to: {NEW_CSV_PATH}")

        return df

    except Exception as e:
        print(f"❌ Error during rebuild: {e}")

# הרצה
rebuilt_df = rebuild_2026_dataset()

"""# Summerize Data weekly comparison"""

def get_weekly_comparison_v2(df):
    today = datetime.now().date()
    periods = [
        (today - timedelta(days=6), today, "This Week"),
        (today - timedelta(days=13), today - timedelta(days=7), "Last Week"),
        (today - timedelta(days=20), today - timedelta(days=14), "2 Weeks Ago")
    ]

    comparison_data = []
    for start, end, label in periods:
        mask = (df['date'].dt.date >= start) & (df['date'].dt.date <= end)
        week_df = df.loc[mask]

        if not week_df.empty:
            # חישוב המדדים לשבוע פעיל
            stats = {
                'label': label,
                'num_runs': len(week_df), # מספר ריצות
                'distance': week_df['distance_km'].sum(),
                'longest_run': week_df['distance_km'].max(), # הריצה הכי ארוכה
                'total_climb': week_df['elevation_gain'].sum(), # טיפוס מצטבר
                'avg_pace': week_df['pace_min_km'].mean(),
                'avg_hr': week_df['avg_hr'].mean(),
                'stride': week_df['stride_length_cm'].mean(),
                'acwr': week_df['acwr'].iloc[-1],
                'efficiency': (week_df['distance_km'].sum() / (week_df['avg_hr'].mean() * (week_df['duration_min'].sum()/60))) if week_df['avg_hr'].mean() > 0 else 0
            }
        else:
            stats = {k: 0 for k in [
                'num_runs', 'distance', 'longest_run', 'total_climb',
                'avg_pace', 'avg_hr', 'stride', 'acwr', 'efficiency'
            ]}
            stats['label'] = label

        comparison_data.append(stats)

    return comparison_data

"""# Send email"""

def send_performance_report_v5(comparison_data):
    SENDER = os.environ.get('sender')
    RECEIVER = os.environ.get('receiver_email')
    PASSWORD = os.environ.get('gramin_report')

    if not SENDER or not RECEIVER or not PASSWORD:
        print("❌ Credentials missing.")
        return

    c = comparison_data
    acwr_val = c[0]['acwr']
    acwr_color = "#27ae60" if 0.8 <= acwr_val <= 1.3 else "#e67e22" if acwr_val < 0.8 else "#e74c3c"

    html_content = f"""
    <div dir="ltr" style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e0e0e0; padding: 25px; border-radius: 15px; background-color: #ffffff;">

        <h2 style="color: #2c3e50; text-align: center; border-bottom: 3px solid #3498db; padding-bottom: 10px; margin-bottom: 10px;">Weekly Running Analytics</h2>
        <p style="text-align: center; color: #7f8c8d; margin-top: 0;">Report for {today.strftime('%B %d, %Y')}</p>

        <div style="background-color: #f8f9fa; border-radius: 10px; padding: 15px; margin-bottom: 25px; border: 1px solid #eee;">
            <h3 style="margin-top: 0; color: #34495e; font-size: 16px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">🏆 Weekly Highlights</h3>
            <table style="width: 100%;">
                <tr>
                    <td style="width: 33%; text-align: center;">
                        <span style="font-size: 11px; color: #7f8c8d; display: block;">Longest Run</span>
                        <b style="font-size: 18px; color: #2980b9;">{c[0]['longest_run']:.1f} km</b>
                    </td>
                    <td style="width: 33%; text-align: center; border-left: 1px solid #ddd; border-right: 1px solid #ddd;">
                        <span style="font-size: 11px; color: #7f8c8d; display: block;">Total Climb</span>
                        <b style="font-size: 18px; color: #2980b9;">{int(c[0]['total_climb'])}m ⛰️</b>
                    </td>
                    <td style="width: 33%; text-align: center;">
                        <span style="font-size: 11px; color: #7f8c8d; display: block;">Consistency</span>
                        <b style="font-size: 18px; color: #2980b9;">{c[0]['num_runs']} Runs</b>
                    </td>
                </tr>
            </table>
        </div>

        <table style="width: 100%; border-collapse: collapse;">
            <thead>
                <tr style="background-color: #3498db; color: white;">
                    <th style="padding: 10px; border: 1px solid #ddd; text-align: left; font-size: 13px;">Metric</th>
                    <th style="padding: 10px; border: 1px solid #ddd; text-align: center; font-size: 13px;">This Week</th>
                    <th style="padding: 10px; border: 1px solid #ddd; text-align: center; font-size: 13px;">Last Week</th>
                    <th style="padding: 10px; border: 1px solid #ddd; text-align: center; font-size: 13px;">2 Weeks Ago</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><b>Total Distance (km)</b><br><small style="color:#95a5a6; font-size:10px;">Weekly volume</small></td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[0]['distance']:.1f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[1]['distance']:.1f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[2]['distance']:.1f}</td>
                </tr>
                <tr style="background-color: #fcfcfc;">
                    <td style="padding: 8px; border: 1px solid #ddd;"><b>Avg Pace</b><br><small style="color:#95a5a6; font-size:10px;">min/km</small></td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[0]['avg_pace']:.2f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[1]['avg_pace']:.2f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[2]['avg_pace']:.2f}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><b>Avg Heart Rate</b><br><small style="color:#95a5a6; font-size:10px;">Cardio effort</small></td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{int(c[0]['avg_hr'])}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{int(c[1]['avg_hr'])}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{int(c[2]['avg_hr'])}</td>
                </tr>
                <tr style="background-color: #fcfcfc;">
                    <td style="padding: 8px; border: 1px solid #ddd;"><b>Stride Length (cm)</b><br><small style="color:#95a5a6; font-size:10px;">Fatigue indicator</small></td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[0]['stride']:.1f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[1]['stride']:.1f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[2]['stride']:.1f}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border: 1px solid #ddd;"><b>Efficiency Score</b><br><small style="color:#95a5a6; font-size:10px;">Dist per heart beat</small></td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[0]['efficiency']:.3f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[1]['efficiency']:.3f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[2]['efficiency']:.3f}</td>
                </tr>
                <tr style="background-color: #fcfcfc;">
                    <td style="padding: 8px; border: 1px solid #ddd;"><b>Load Ratio (ACWR)</b><br><small style="color:#95a5a6; font-size:10px;">Injury prevention</small></td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-weight: bold; color: {acwr_color};">{acwr_val:.2f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[1]['acwr']:.2f}</td>
                    <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{c[2]['acwr']:.2f}</td>
                </tr>
            </tbody>
        </table>

        <div style="margin-top: 25px; padding: 15px; background-color: #f0f7fd; border-left: 5px solid #3498db; border-radius: 8px;">
            <p style="margin: 0; font-size: 14px; color: #2c3e50; line-height: 1.5;">
                <b>🏃 Coach's Analysis:</b><br>
                { "Caution: High workload. Focus on active recovery." if acwr_val > 1.3
                  else "Maintenance: Low load. Good time for a speed session." if acwr_val < 0.8
                  else "Optimal: Training load is perfectly balanced. Keep it up!" }
            </p>
        </div>
    </div>
    """

    msg = MIMEMultipart()
    msg['Subject'] = f"Weekly Running Analysis | {today.strftime('%d/%m/%Y')}"
    msg['From'] = SENDER
    msg['To'] = RECEIVER
    msg.attach(MIMEText(html_content, 'html'))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SENDER, PASSWORD)
            server.send_message(msg)
        print("✅ Full Professional Report (V5) sent successfully!")
    except Exception as e:
        print(f"❌ Error: {e}")

# הפעלה
comp_data = get_weekly_comparison_v2(rebuilt_df)
send_performance_report_v5(comp_data)
